name: healthadmin
description: A healthcare administration app for clinics and doctors.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0

  # State Management
  provider: ^6.1.5

  # Google Maps
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.1
  permission_handler: ^11.0.1

  # UI Components
  cupertino_icons: ^1.0.8
  flutter_rating_bar: ^4.0.1

  # Navigation
  go_router: ^12.1.3

  # Utilities
  intl: ^0.18.1
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true

  # Assets section
  assets:
    - assets/images/Logo.png
    - assets/images/doctor-placeholder.png
